site_name: Nao机器人手册
nav:
    - '简介': index.md
    - '基本操作': basic.md
    - '机器人运动': motion.md
    - '机器人视觉': vision.md
    - '机器人听觉': audio.md
    - '机器人情绪感知': emotion.md
    - '机器人跳舞实例解析': dance.md
    - '机器人踢球实例解析': kick_ball.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: "#"